# File: project/world_cities.py
# Author: Abdul Rafay (rafaya@bu.edu), 4/27/2026
# Description: Curated list of ~350 major world cities for the city search datalist.
#              Each entry is formatted as "City, Country" for display and API lookup.

WORLD_CITIES = sorted([
    # --- North America: United States ---
    "New York, United States",
    "Los Angeles, United States",
    "Chicago, United States",
    "Houston, United States",
    "Phoenix, United States",
    "Philadelphia, United States",
    "San Antonio, United States",
    "San Diego, United States",
    "Dallas, United States",
    "San Jose, United States",
    "Austin, United States",
    "San Francisco, United States",
    "Columbus, United States",
    "Seattle, United States",
    "Denver, United States",
    "Boston, United States",
    "Nashville, United States",
    "Las Vegas, United States",
    "Detroit, United States",
    "Memphis, United States",
    "Atlanta, United States",
    "Miami, United States",
    "Minneapolis, United States",
    "Tampa, United States",
    "New Orleans, United States",
    "Honolulu, United States",
    "Pittsburgh, United States",
    "Raleigh, United States",
    "Orlando, United States",
    "Cleveland, United States",
    "Cincinnati, United States",
    "St. Louis, United States",
    "Kansas City, United States",
    "Sacramento, United States",
    "Portland, United States",
    "Indianapolis, United States",
    "Charlotte, United States",
    "Salt Lake City, United States",
    "Buffalo, United States",
    "Richmond, United States",
    "Hartford, United States",
    "Dearborn, United States",
    "Albuquerque, United States",
    "Tucson, United States",
    # --- North America: Canada ---
    "Toronto, Canada",
    "Montreal, Canada",
    "Vancouver, Canada",
    "Calgary, Canada",
    "Edmonton, Canada",
    "Ottawa, Canada",
    "Winnipeg, Canada",
    "Quebec City, Canada",
    "Halifax, Canada",
    # --- North America: Mexico ---
    "Mexico City, Mexico",
    "Guadalajara, Mexico",
    "Monterrey, Mexico",
    "Puebla, Mexico",
    "Tijuana, Mexico",
    "Cancun, Mexico",
    "Leon, Mexico",
    # --- Central America & Caribbean ---
    "Guatemala City, Guatemala",
    "San Jose, Costa Rica",
    "Panama City, Panama",
    "Havana, Cuba",
    "Kingston, Jamaica",
    "Santo Domingo, Dominican Republic",
    # --- South America ---
    "Sao Paulo, Brazil",
    "Buenos Aires, Argentina",
    "Lima, Peru",
    "Bogota, Colombia",
    "Santiago, Chile",
    "Rio de Janeiro, Brazil",
    "Brasilia, Brazil",
    "Belo Horizonte, Brazil",
    "Fortaleza, Brazil",
    "Manaus, Brazil",
    "Salvador, Brazil",
    "Curitiba, Brazil",
    "Porto Alegre, Brazil",
    "Caracas, Venezuela",
    "Quito, Ecuador",
    "Guayaquil, Ecuador",
    "Montevideo, Uruguay",
    "Asuncion, Paraguay",
    "La Paz, Bolivia",
    "Santa Cruz, Bolivia",
    "Medellin, Colombia",
    "Cali, Colombia",
    "Barranquilla, Colombia",
    "Cordoba, Argentina",
    "Rosario, Argentina",
    # --- Europe: Western ---
    "London, United Kingdom",
    "Paris, France",
    "Berlin, Germany",
    "Madrid, Spain",
    "Rome, Italy",
    "Amsterdam, Netherlands",
    "Vienna, Austria",
    "Barcelona, Spain",
    "Hamburg, Germany",
    "Munich, Germany",
    "Brussels, Belgium",
    "Lisbon, Portugal",
    "Dublin, Ireland",
    "Zurich, Switzerland",
    "Geneva, Switzerland",
    "Milan, Italy",
    "Frankfurt, Germany",
    "Lyon, France",
    "Marseille, France",
    "Rotterdam, Netherlands",
    "Cologne, Germany",
    "Stuttgart, Germany",
    "Edinburgh, United Kingdom",
    "Glasgow, United Kingdom",
    "Manchester, United Kingdom",
    "Birmingham, United Kingdom",
    "Liverpool, United Kingdom",
    "Leeds, United Kingdom",
    "Toulouse, France",
    "Nice, France",
    "Bordeaux, France",
    "Dusseldorf, Germany",
    "Leipzig, Germany",
    "Antwerp, Belgium",
    "Porto, Portugal",
    "Seville, Spain",
    "Valencia, Spain",
    "Naples, Italy",
    "Turin, Italy",
    "Florence, Italy",
    "Luxembourg City, Luxembourg",
    # --- Europe: Northern ---
    "Stockholm, Sweden",
    "Copenhagen, Denmark",
    "Helsinki, Finland",
    "Oslo, Norway",
    "Reykjavik, Iceland",
    "Gothenburg, Sweden",
    "Malmo, Sweden",
    "Aarhus, Denmark",
    "Bergen, Norway",
    # --- Europe: Eastern ---
    "Warsaw, Poland",
    "Budapest, Hungary",
    "Prague, Czech Republic",
    "Bucharest, Romania",
    "Sofia, Bulgaria",
    "Zagreb, Croatia",
    "Bratislava, Slovakia",
    "Ljubljana, Slovenia",
    "Belgrade, Serbia",
    "Sarajevo, Bosnia and Herzegovina",
    "Skopje, North Macedonia",
    "Tirana, Albania",
    "Krakow, Poland",
    "Wroclaw, Poland",
    "Gdansk, Poland",
    "Riga, Latvia",
    "Tallinn, Estonia",
    "Vilnius, Lithuania",
    "Athens, Greece",
    "Thessaloniki, Greece",
    # --- Russia & Former Soviet ---
    "Moscow, Russia",
    "Saint Petersburg, Russia",
    "Novosibirsk, Russia",
    "Yekaterinburg, Russia",
    "Kazan, Russia",
    "Nizhny Novgorod, Russia",
    "Chelyabinsk, Russia",
    "Samara, Russia",
    "Ufa, Russia",
    "Krasnoyarsk, Russia",
    "Kyiv, Ukraine",
    "Kharkiv, Ukraine",
    "Odessa, Ukraine",
    "Minsk, Belarus",
    # --- Central Asia ---
    "Almaty, Kazakhstan",
    "Astana, Kazakhstan",
    "Tashkent, Uzbekistan",
    "Samarkand, Uzbekistan",
    "Bishkek, Kyrgyzstan",
    "Dushanbe, Tajikistan",
    "Ashgabat, Turkmenistan",
    "Baku, Azerbaijan",
    "Tbilisi, Georgia",
    "Yerevan, Armenia",
    # --- Middle East: Turkey ---
    "Istanbul, Turkey",
    "Ankara, Turkey",
    "Izmir, Turkey",
    "Bursa, Turkey",
    "Antalya, Turkey",
    "Adana, Turkey",
    # --- Middle East: Iran ---
    "Tehran, Iran",
    "Isfahan, Iran",
    "Mashhad, Iran",
    "Tabriz, Iran",
    "Shiraz, Iran",
    "Karaj, Iran",
    # --- Middle East: Arabian Peninsula ---
    "Riyadh, Saudi Arabia",
    "Jeddah, Saudi Arabia",
    "Mecca, Saudi Arabia",
    "Medina, Saudi Arabia",
    "Dammam, Saudi Arabia",
    "Dubai, United Arab Emirates",
    "Abu Dhabi, United Arab Emirates",
    "Sharjah, United Arab Emirates",
    "Doha, Qatar",
    "Kuwait City, Kuwait",
    "Manama, Bahrain",
    "Muscat, Oman",
    "Sana'a, Yemen",
    "Aden, Yemen",
    # --- Middle East: Levant & Iraq ---
    "Beirut, Lebanon",
    "Damascus, Syria",
    "Aleppo, Syria",
    "Baghdad, Iraq",
    "Basra, Iraq",
    "Erbil, Iraq",
    "Amman, Jordan",
    "Jerusalem, Israel",
    "Tel Aviv, Israel",
    # --- North Africa ---
    "Cairo, Egypt",
    "Alexandria, Egypt",
    "Casablanca, Morocco",
    "Rabat, Morocco",
    "Marrakesh, Morocco",
    "Fez, Morocco",
    "Tangier, Morocco",
    "Tunis, Tunisia",
    "Tripoli, Libya",
    "Algiers, Algeria",
    "Oran, Algeria",
    # --- East & Horn of Africa ---
    "Addis Ababa, Ethiopia",
    "Nairobi, Kenya",
    "Dar es Salaam, Tanzania",
    "Kampala, Uganda",
    "Mogadishu, Somalia",
    "Khartoum, Sudan",
    "Mombasa, Kenya",
    "Zanzibar, Tanzania",
    # --- West Africa ---
    "Lagos, Nigeria",
    "Kano, Nigeria",
    "Ibadan, Nigeria",
    "Abuja, Nigeria",
    "Accra, Ghana",
    "Dakar, Senegal",
    "Abidjan, Cote d'Ivoire",
    "Bamako, Mali",
    "Conakry, Guinea",
    "Ouagadougou, Burkina Faso",
    "Niamey, Niger",
    "Yaounde, Cameroon",
    "Douala, Cameroon",
    # --- Central & Southern Africa ---
    "Kinshasa, Democratic Republic of the Congo",
    "Luanda, Angola",
    "Lusaka, Zambia",
    "Harare, Zimbabwe",
    "Maputo, Mozambique",
    "Antananarivo, Madagascar",
    "Cape Town, South Africa",
    "Johannesburg, South Africa",
    "Durban, South Africa",
    "Pretoria, South Africa",
    "Kigali, Rwanda",
    # --- South Asia: India ---
    "Mumbai, India",
    "Delhi, India",
    "Bangalore, India",
    "Hyderabad, India",
    "Chennai, India",
    "Kolkata, India",
    "Pune, India",
    "Ahmedabad, India",
    "Surat, India",
    "Jaipur, India",
    "Lucknow, India",
    "Kanpur, India",
    "Nagpur, India",
    "Patna, India",
    "Indore, India",
    "Bhopal, India",
    "Agra, India",
    "Varanasi, India",
    "Ludhiana, India",
    "Nashik, India",
    # --- South Asia: Pakistan ---
    "Karachi, Pakistan",
    "Lahore, Pakistan",
    "Islamabad, Pakistan",
    "Faisalabad, Pakistan",
    "Rawalpindi, Pakistan",
    "Peshawar, Pakistan",
    "Quetta, Pakistan",
    "Multan, Pakistan",
    # --- South Asia: Bangladesh & Others ---
    "Dhaka, Bangladesh",
    "Chittagong, Bangladesh",
    "Sylhet, Bangladesh",
    "Kathmandu, Nepal",
    "Colombo, Sri Lanka",
    "Kabul, Afghanistan",
    # --- East Asia: China ---
    "Beijing, China",
    "Shanghai, China",
    "Guangzhou, China",
    "Shenzhen, China",
    "Chengdu, China",
    "Tianjin, China",
    "Chongqing, China",
    "Wuhan, China",
    "Nanjing, China",
    "Hangzhou, China",
    "Shenyang, China",
    "Harbin, China",
    "Qingdao, China",
    "Kunming, China",
    "Zhengzhou, China",
    "Urumqi, China",
    # --- East Asia: Japan & Korea ---
    "Tokyo, Japan",
    "Osaka, Japan",
    "Nagoya, Japan",
    "Sapporo, Japan",
    "Fukuoka, Japan",
    "Kobe, Japan",
    "Kyoto, Japan",
    "Hiroshima, Japan",
    "Seoul, South Korea",
    "Busan, South Korea",
    "Incheon, South Korea",
    "Daegu, South Korea",
    # --- Southeast Asia ---
    "Jakarta, Indonesia",
    "Surabaya, Indonesia",
    "Bandung, Indonesia",
    "Medan, Indonesia",
    "Makassar, Indonesia",
    "Manila, Philippines",
    "Quezon City, Philippines",
    "Davao, Philippines",
    "Cebu, Philippines",
    "Kuala Lumpur, Malaysia",
    "Penang, Malaysia",
    "Singapore, Singapore",
    "Bangkok, Thailand",
    "Chiang Mai, Thailand",
    "Ho Chi Minh City, Vietnam",
    "Hanoi, Vietnam",
    "Da Nang, Vietnam",
    "Yangon, Myanmar",
    "Mandalay, Myanmar",
    "Phnom Penh, Cambodia",
    "Vientiane, Laos",
    "Taipei, Taiwan",
    # --- Oceania ---
    "Sydney, Australia",
    "Melbourne, Australia",
    "Brisbane, Australia",
    "Perth, Australia",
    "Adelaide, Australia",
    "Canberra, Australia",
    "Gold Coast, Australia",
    "Auckland, New Zealand",
    "Wellington, New Zealand",
    "Christchurch, New Zealand",
    "Port Moresby, Papua New Guinea",
    "Suva, Fiji",
])
