# Generated by Django 6.0.1 on 2026-04-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HijriCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('hijri_day', models.IntegerField()),
                ('hijri_month', models.TextField()),
                ('hijri_year', models.IntegerField()),
                ('holiday_name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('zuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.city')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madhab', models.TextField(choices=[('Standard', 'Standard (Imam Shafi, Hanbali, Maliki)'), ('Hanafi', 'Hanafi')], default='Standard')),
                ('calculation_method', models.TextField(choices=[('ISNA', 'Islamic Society of North America (ISNA)'), ('MWL', 'Muslim World League (MWL)'), ('Egyptian', 'Egyptian General Authority of Survey'), ('UmmAlQura', 'Umm al-Qura University, Makkah')], default='ISNA')),
                ('notification_preference', models.BooleanField(default=True)),
                ('display_language', models.TextField(default='English')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='project.city')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cities', to='project.profile')),
            ],
            options={
                'unique_together': {('profile', 'city')},
            },
        ),
    ]
